# Generated by Django 5.1.2 on 2024-11-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experimento", "0004_trial_participant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentsession",
            name="last_response",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
