# Generated by Django 4.1 on 2024-11-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experimento", "0007_alter_trial_d1"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentsession",
            name="current_trial",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="experimentsession",
            name="total_trials",
            field=models.IntegerField(default=10),
        ),
    ]
