# Generated by Django 4.1 on 2024-11-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experimento", "0011_experimentsession_current_d1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experimentsession",
            name="current_d1",
        ),
        migrations.RemoveField(
            model_name="experimentsession",
            name="current_trial",
        ),
        migrations.RemoveField(
            model_name="experimentsession",
            name="total_trials",
        ),
    ]
