# Generated by Django 4.1 on 2024-11-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimento', '0018_trial_ado_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='ado_type',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
