# Generated by Django 4.1 on 2024-11-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experimento", "0008_experimentsession_current_trial_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experimentsession",
            name="current_trial",
        ),
        migrations.RemoveField(
            model_name="experimentsession",
            name="total_trials",
        ),
    ]
