# Generated by Django 4.1 on 2024-11-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experimento", "0009_remove_experimentsession_current_trial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentsession",
            name="current_trial",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="experimentsession",
            name="total_trials",
            field=models.IntegerField(default=10),
        ),
    ]
