# Generated by Django 4.1 on 2024-11-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experimento", "0010_experimentsession_current_trial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentsession",
            name="current_d1",
            field=models.FloatField(default=0.0),
        ),
    ]
