# Generated by Django 5.1.2 on 2024-11-20 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experimento", "0016_trial_participant_id_random"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trial",
            name="participant_id_random",
        ),
    ]
