# Generated by Django 4.1 on 2024-11-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimento', '0017_remove_trial_participant_id_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='ado_type',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
