# Generated by Django 5.1.3 on 2024-11-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimento', '0020_alter_trial_ado_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentsession',
            name='prior_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='ado_type',
            field=models.IntegerField(default=1),
        ),
    ]
